version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-production
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/user_management
      - NODE_ENV=production
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-production
    ports:
      - "8089:80"
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
